### ISSUE TITLE
关于博客中的一个问题

### ISSUE THREAD

**Issue by zhaopeifei** [stephenzhao/hexo-theme-damon#1]
您好，我看了您的[前端面试之js相关问题（一）](http://stephenzhao.github.io/2016/08/19/Front-end-Job-Interview-Questions/)，里面应该有个错误的。因为在您的博客上没有看多可以评论的地方，就来这里了。

```
var a = 1;  
function b() {  
    a = 10;  
    return;  
    function a() {}  
}  
b();  
console.log(a); 
// 输出1 由于函数声明提升，b内的实际是这样：
// function b() {  
//    var a;
//    a = 10;  
//    return;  
//    function a() {}  
// }
//正确的顺序应该为：
// function b() {  
//    function a() {}  
//    a = 10;  
//    return;  
// }
```

这里它的执行逻辑应该是，先进行预编译，所以先执行function a(){}，然后会进行对a的赋值操作，最后返回return。如果没有function a(){}的话，这里的a=10会导致全局变量的a被赋值为10的。所以，这个例子其实并不好，不太适合来说明预编译的过程。顺便推荐一下《你不知道的JS》，里面关于这部分讲的很详细。

**Comment by stephenzhao** [comment]
谢谢你的指正，刚看到。文章也在 前端杂货铺》https://zhuanlan.zhihu.com/jscss 
可以在下面评论。。也欢迎您来投稿。
